# Used Car Market Analysis

## Objective

This project demonstrates data cleaning, exploratory data analysis, and interactive visualization using Python.

Dataset: Quikr Used Cars Dataset

Tools:
- Python
- Pandas
- Plotly
- Dash
- Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv("../data/quikr_car.csv")

df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [3]:
df.info()

df.shape

df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [4]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

Observation:

The dataset contains missing values in fuel_type and kms_driven fields.

In [5]:
df = df[df["year"].str.isnumeric()]

df["year"] = df["year"].astype(int)

In [6]:
df = df[df["Price"] != "Ask For Price"]

df["Price"] = df["Price"].str.replace(",", "")

df["Price"] = df["Price"].astype(int)

In [7]:
df["kms_driven"] = df["kms_driven"].str.replace(" kms", "")

df["kms_driven"] = df["kms_driven"].str.replace(",", "")

df = df[df["kms_driven"].str.isnumeric()]

df["kms_driven"] = df["kms_driven"].astype(int)

In [8]:
df.dropna(inplace=True)

In [9]:
df.to_csv("../data/cleaned_car_data.csv", index=False)